apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: dev
images:
- name: docker.io/jmuachifi/flask-app-argocd
  newTag: f9ba67bd0cd4bf5d613e72e3ed2adaee38ef55d9
