# argocd-app.yaml is the manifest file that will be used to create the ArgoCD application.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-dev-app-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/jmuachifi/flask-app-argocd.git'
    path: deployment/dev
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argo-dev-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
