name: CI Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  DOCKER_IMAGE: jmuachifi/flask-app-argocd
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  APP_VERSION: ''

jobs:
    build:
        name: Build Docker Image
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout Code
          uses: actions/checkout@v3
    
        - name: Set APP_VERSION
          run: |
            cd app
            echo "APP_VERSION=$(grep -E -o '(version = )(.*)' release.txt | cut -d\" -f2)" >> $GITHUB_ENV
    
        - name: Log in to Docker Hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
        - name: Build and Push Docker Image with Kaniko
          run: |
            docker run \
              -v ${GITHUB_WORKSPACE}:/workspace \
              -v /kaniko/.docker:/kaniko/.docker \
              gcr.io/kaniko-project/executor:v1.9.0-debug \
              --context /workspace \
              --dockerfile /workspace/Dockerfile \
              --destination ${DOCKER_IMAGE}:${APP_VERSION} \
              --destination ${DOCKER_IMAGE}:latest \
              --customPlatform linux/arm

    deploy-dev:
        name: Deploy to Dev Environment
        runs-on: ubuntu-latest
        needs: build

        steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Install kustomize
          run: |
                curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
                sudo mv kustomize /usr/local/bin/

        - name: Update Kustomization for Dev
          run: |
            cd deployment/dev
            kustomize edit set image ${DOCKER_IMAGE}:${APP_VERSION}
            cat kustomization.yaml

        - name: Commit and Push Changes
          run: |
                git remote set-url origin https://jmuachifi:${{ secrets.GH_PAT }}@github.com/jmuachifi/flask-app-argocd.git
                git config --global user.email "github-actions@github.com"
                git config --global user.name "Cloud Expert"
                git checkout -B main
                git commit -am '[skip ci] DEV manifest-image update'
                git push origin main

    deploy-prod:
        name: Deploy to Prod Environment
        runs-on: ubuntu-latest
        needs: build
        if: github.event_name == 'workflow_dispatch'

        steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Install kustomize
          run: |
            curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
            sudo mv kustomize /usr/local/bin/

        - name: Update Kustomization for Prod
          run: |
                git checkout -B main
                git pull origin main
                cd deployment/prod
                kustomize edit set image ${DOCKER_IMAGE}:${APP_VERSION}
                cat kustomization.yaml

        - name: Commit and Push Changes
          run: |
                git remote set-url origin https://jmuachifi:${{ secrets.GH_PAT }}@github.com/jmuachifi/flask-app-argocd.git
                git config --global user.email "github-actions@github.com"
                git config --global user.name "Cloud Expert"
                git commit -am '[skip ci] PROD manifest-image update'
                git push origin main
