name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t docker.io/jmuachifi/flask-app-argocd:${{ github.sha }} -t docker.io/jmuachifi/flask-app-argocd:latest .
        docker push docker.io/jmuachifi/flask-app-argocd:${{ github.sha }}
        docker push docker.io/jmuachifi/flask-app-argocd:latest

  update_kustomization_dev:
    name: Update Kustomization for Dev Environment
    runs-on: ubuntu-latest
    needs: build_image

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Replace Image Tag in kustomization.yaml
      run: |
        sed -i "s/newTag: .*/newTag: ${{ github.sha }}/" deployment/dev/kustomization.yaml
        cat deployment/dev/kustomization.yaml

    - name: Commit and Push Changes
      run: |
        git remote set-url origin https://jmuachifi:${{ secrets.GH_PAT }}@github.com/jmuachifi/flask-app-argocd.git
        git config --global user.email "github-actions@github.com"
        git config --global user.name "Cloud Expert"
        git checkout -B main
        git commit -am '[skip ci] DEV manifest-image update Update to ${{ github.sha }} '
        git push origin main

  update_kustomization_prod:
            name: Update Kustomization for Prod Environment
            runs-on: ubuntu-latest
            needs: build_image
            if: github.event_name == 'workflow_dispatch'
        
            steps:
            - name: Checkout Code
              uses: actions/checkout@v2
        
            - name: Replace Image Tag in kustomization.yaml
              run: |
                sed -i "s/newTag: .*/newTag: ${{ github.sha }}/" deployment/prod/kustomization.yaml
                cat deployment/prod/kustomization.yaml
        
            - name: Commit and Push Changes
              run: |
                git remote set-url origin https://jmuachifi:${{ secrets.GH_PAT }}@github.com/jmuachifi/flask-app-argocd.git
                git config --global user.email "github-actions@github.com"
                git config --global user.name "Cloud Expert"
                git commit -am '[skip ci] PROD manifest-image update'
                git push origin main
        
